sudo: false
language: python

os: linux
dist: trusty
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - CHAINER_VERSION="chainer<3"
  - CHAINER_VERSION="chainer"
  - CHAINER_VERSION="prerelease"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install codecov
  - pip install mock
  - conda install pip pytest pytest-cov
  - conda install -c rdkit rdkit
  - if [ "${CHAINER_VERSION}" = "prerelease" ]; then
      pip install --pre chainer;
    else
      pip install "${CHAINER_VERSION}";
    fi
  - pip install --no-cache-dir -e .

script:
  - pytest --cov=./ -m "not (gpu or slow)" tests

after_success:
  - codecov